spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/aiservice
      database: aiservice

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.type.header: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  topic:
    name: activity-events

gemini:
  api:
    key: AIzaSyAlSOgRjmA9OlO6Khk8q0tAe0pLPvGmIXw
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
