eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# spring:
#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           jwk-set-uri: http://localhost:8181/realms/master/protocol/openid-connect/certs

#   cloud:
#     gateway:
#       routes:
#         - id: USER-SERVICE
#           uri: lb://USER-SERVICE
#           predicates:
#             - Path=/api/users/**

#         - id: ACTIVITY-SERVICE
#           uri: lb://ACTIVITY-SERVICE
#           predicates:
#             - Path=/api/activities/**

#         - id: AISERVICE
#           uri: lb://AISERVICE
#           predicates:
#             - Path=/api/recommendations/**

server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/master

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: ACTIVITY-SERVICE
          uri: lb://ACTIVITY-SERVICE
          predicates:
            - Path=/api/activities/**

        - id: AISERVICE
          uri: lb://AISERVICE
          predicates:
            - Path=/api/recommendations/**
